export default {
  'ru': {
    'store.vk.online': 'был в сети 19 минут назад',
    'titles.home': 'Развлекательный сайт',
    'titles.vk': 'Создать переписку Вконтакте',
    'titles.fb': 'Создать переписку Фейсбук',
    'menu.vk': 'ВКонтакте',
    'menu.fb': 'Фейсбук',
    'content.dialog.title': 'Предварительный показ',
    'content.back': 'Назад',
    'content.writeMessage': 'Напишите сообщение...',
    'config.top.title': 'Верхняя часть',
    'config.top.online': 'Время в сети',
    'config.top.mobile': 'С мобильного',
    'config.current.title': 'Текущий пользователь',
    'config.current.fullName': 'Полное имя',
    'config.current.message': 'Добавить сообщение',
    'config.current.avatar': 'Аватар',
    'config.current.msg.title': 'Сообщение пользователя',
    'config.msg.label': 'Сообщение',
    'config.msgTime.label': 'Время отправки',
    'config.msgTime.placeholder': 'пример: 14:00',
    'config.companion.msg.title': 'Сообщение собеседник',
    'config.companion.title': 'Собеседник',
    'config.companion.fullName': 'Полное имя',
    'config.companion.avatar': 'Аватар',
    'config.companion.message': 'Добавить сообщение',
    'config.content.title': 'Контент',
    'config.content.height': 'Высота контента',
    'config.content.separator': 'Добавить разделитель',
    'config.content.separator.label': 'Текст разделителя',
    'config.content.separator.placeholder': 'пример: 6 ноября',
    'config.sections.title': 'Разделы',
    'config.sections.top': 'Показать верхнюю часть',
    'config.sections.bottom': 'Показать нижнюю часть',
    'config.imageSelect.link': 'Ссылка на аватар',
    'config.imageSelect.button': 'Добавить',
    'config.imageSelect.upload': 'Загрузить аватар',
    'download': 'скачать',
    'cancel': 'Отменить',
    'add': 'Добавить'
  },
  'en': {
    'store.vk.online': 'was online 19 minutes ago',
    'titles.home': 'Entertaining web site',
    'titles.vk': 'Create a correspondence VKontakte',
    'titles.fb': 'Create a correspondence FaceBook',
    'menu.vk': 'VKontakte',
    'menu.fb': 'Facebook',
    'content.dialog.title': 'Preview',
    'content.back': 'Back',
    'content.writeMessage': 'Write a message...',
    'config.top.title': 'Top part',
    'config.top.online': 'Online time',
    'config.top.mobile': 'From mobile',
    'config.current.title': 'Current user',
    'config.current.fullName': 'Full name',
    'config.current.avatar': 'Avatar',
    'config.current.message': 'Add new message',
    'config.current.msg.title': 'User message',
    'config.msg.label': 'message',
    'config.msgTime.label': 'User message',
    'config.msgTime.placeholder': 'example: 14:00',
    'config.companion.msg.title': 'Interlocutor message',
    'config.companion.title': 'Interlocutor',
    'config.companion.fullName': 'Full name',
    'config.companion.avatar': 'Avatar',
    'config.companion.message': 'Add new message',
    'config.content.title': 'Content',
    'config.content.height': 'Content height',
    'config.content.separator': 'Add separator',
    'config.content.separator.label': 'Separator text',
    'config.content.separator.placeholder': 'example: november 6',
    'config.sections.title': 'Sections',
    'config.sections.top': 'Show top side',
    'config.sections.bottom': 'Show bottom side',
    'config.imageSelect.link': 'Avatar link',
    'config.imageSelect.button': 'Add',
    'config.imageSelect.upload': 'Upload image',
    'download': 'download',
    'cancel': 'Cancel',
    'add': 'Add'
  }
};
